### ISSUE TITLE
REQ: Custom data on slots

### ISSUE THREAD

**Issue by HybridFox** [radiopanel/radiopanel#3]

**Comment by ArranLH** [comment]
Custom data on slots i.e. being able to link content types, users, text fields etc.

**Comment by HybridFox** [comment]
@ArranLH how would you see this? Some extra fields when booking a show?

**Comment by ArranLH** [comment]
Possibly being able to attach content items to slots, and additional fields?

**Comment by HybridFox** [comment]
So just like the custom profile fields then? But for slots

**Comment by ArranLH** [comment]
Correct. With the ability to have the nested content too :)

Ex. Linking a slot to a content type of "show"
