### ISSUE TITLE
bug: Maximum slot length is ignored

### ISSUE THREAD

**Issue by TechPhil** [radiopanel/radiopanel#32]
# Bug Report

**Radiopanel version:**

0.0.1-alpha.21

**Current behavior:**

The maximum slot length option has no effect. Users can book slots longer than the limit.

**Expected behavior:**

Slots longer than the maximum should be blocked.

**Comment by HybridFox** [comment]
Cannot seem to reproduce this, can you verify the time is actually set?

**Comment by TechPhil** [comment]
reproducible on latest version - 
<img width="1322" alt="Screenshot 2021-06-30 at 19 30 36" src="https://user-images.githubusercontent.com/26381564/124013232-f535b380-d9d9-11eb-8cf8-293d0b8a6add.png">
<img width="1302" alt="Screenshot 2021-06-30 at 19 30 21" src="https://user-images.githubusercontent.com/26381564/124013238-f961d100-d9d9-11eb-803c-cf2875dc3620.png">

Unsure where this value is stored in database, otherwise would show this as well

**Comment by HybridFox** [comment]
Is this with the drag & drop or are you manually editing the times in the popup?

**Comment by TechPhil** [comment]
Manually editing times in popup. Also applies when creating a new slot. Have not tried drag and drop.

**Comment by HybridFox** [comment]
Gotcha, the drag & drop does keep the max time in mind but not the manual edit, i'll code something in for it

**Comment by TechPhil** [comment]
👍
