### ISSUE TITLE
feat: Allow content types to be assigned types

### ISSUE THREAD

**Issue by TechPhil** [radiopanel/radiopanel#33]
# Feature Request

**Describe the Feature Request**

Add custom input types to content types

**Describe Preferred Solution**

Allow for fields to be specifically bound to things such as date-time, color, etc. in content types.

**Additional Context**

Change 'text field' to 'generic input', and allow that input type to be changed.

**If the feature request is approved, would you be willing to submit a PR?**
if i knew how to code then sure

**Comment by HybridFox** [comment]
Fixed in #37
