### ISSUE TITLE
bug: repeaters only return 20 items

### ISSUE THREAD

**Issue by ArranLH** [radiopanel/radiopanel#44]
# Bug Report

**Radiopanel version:**
0.0.1-alpha.23

**Current behavior:**
When using repeaters in content items, it only retrieves and allows searching of a maximum of 20 items, which is problematic if you have more than 20.

**Expected behavior:**
Either returns more entries on start, or searches as you type.

**Steps to reproduce:**
Set up a content item with a repeater and have more than 20 items in the repeater (repeater type content)
**Related code:**

![image](https://user-images.githubusercontent.com/44932529/124780695-b7391200-df3a-11eb-9a6d-c2d715edc3d5.png)
```
insert short code snippets here
```

**Other information:**

**Comment by HybridFox** [comment]
Fixed in fa5649d878ba791d0bb2a803d3d3634d2d8d72b3
