### ISSUE TITLE
bug: Email sending fails (openssl error)

### ISSUE THREAD

**Issue by TechPhil** [radiopanel/radiopanel#47]
# Bug Report

**Radiopanel version:**

1.0.0-rc.2

**Current behavior:**

Emails do not send - Nest error - 
```
radiopanel-api | [Nest] 1   - 08/21/2021, 8:24:59 PM   [ExceptionsHandler] 140416028577096:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
radiopanel-api |  +6662ms
radiopanel-api | Error: 140416028577096:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
radiopanel-api |
```

**Expected behavior:**

Emails should send without error

**Steps to reproduce:**

Initiate action that causes an email to be sent, i.e. inviting user

**Other information:**

Email credentials are definitely correct - can use same credentials and host/port to send email manually

**Comment by HybridFox** [comment]
Possibly SSL error on the mai lserver?

**Comment by TechPhil** [comment]
Not that I can tell - we don't tend to use the email system often so not a huge issue for us. Will monitor on our end and keep you posted

**Comment by HybridFox** [comment]
Aight, you can always hit me up with the server details and i can take a look at it

**Comment by TechPhil** [comment]
Turns out our email provider had decided it would be a great idea to change almost everything about their configuration regarding SSL and not tell anyone. All resolved now.

Closing.
