### ISSUE TITLE
bug: Customisation - Login Page Background Not Working

### ISSUE THREAD

**Issue by ItsDestinyDev** [radiopanel/radiopanel#53]
# Bug Report

**RadioPanel version:**

v1.0.0-rc.16

**Current behavior:**

Well. Long story short. We have a Login Page Background set and it is not displaying.

**Expected behavior:**

It shows the image.

**Steps to reproduce:**

Set an Image for background 

**Other information:**

u still have roles on my panel so u can use that to see the issue

**Comment by TechPhil** [comment]
I know I'm not Felikx but any console errors? Does the image appear in any network requests or in the Sources tab?

**Comment by ItsDestinyDev** [comment]
No Errors In Console and it is not Requested as it is not seen in the Network tab

**Comment by TechPhil** [comment]
Hmm. I'm presuming that the default background is still being displayed?
In the Network tab, there should be an API request to the `/api/v1/tenants/customisation` endpoint - could you copy the response from that?

**Comment by ItsDestinyDev** [comment]
```
{
   "logo":"/uploads/Vize RadioPanel Logo.png",
   "primaryColor":"#6bff9f",
   "authBackground":"/uploads/Vize RadioPanel Background.png",
   "authMethods":[
      {
         "uuid":"7134f241-7c0e-4ecf-93c7-3961a1965ff7",
         "name":"Discord",
         "type":"discord"
      }
   ]
}
```

**Comment by ItsDestinyDev** [comment]
It looks like it an issue with
https://github.com/radiopanel/radiopanel/blob/fbdcee1ec32ab07b459189bcc43c4e1283bb7e24/app/src/app/auth/pages/login/login.page.html#L30

**Comment by TechPhil** [comment]
Yeah, thats the line. Can you inspect the element - what background image is it trying to load? Still the default?

**Comment by HybridFox** [comment]
So breaks with space in the name? Weird 🤔

**Comment by TechPhil** [comment]
I presume it is something related to how background-image treats URLs, although as I type this I realise it's obviously something going wrong with the conditional. As far as I know the `+` symbol is treated identically to a space in URLs, so potentially something API side to fix that?

**Comment by HybridFox** [comment]
Fixed in https://github.com/radiopanel/radiopanel/releases/tag/v1.0.0-rc.18
