### ISSUE TITLE
Customisable icons for content types/page types

### ISSUE THREAD

**Issue by ArranLH** [radiopanel/radiopanel#7]
Would be nice to be able to customise icons for the content types
![image](https://user-images.githubusercontent.com/44932529/121082654-4f29cb80-c7d6-11eb-9965-603fc7b748a0.png)

**Comment by mrnat7471** [comment]
maybe from the fontawesome?

**Comment by HybridFox** [comment]
We currently don't have font awesome, only unicons. They're nice then fontawesome eitherway
